# Generated by Django 4.2.9 on 2024-02-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_studentdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='mobile',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
